import{a as d,T as l}from"./assets/vendor-cc1203f3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=c(e);fetch(e.href,s)}})();const u=d.create({baseURL:"https://your-energy.b.goit.study/api",headers:{Accept:"application/json"}}),p=async o=>{var c,r;const t=await u.post("/subscription",{email:o});if((c=t.data)!=null&&c.error)throw new Error(((r=t.data)==null?void 0:r.error)||"Subscription failed");return t.data},f=async(o="Muscles",t=1)=>{const r=window.innerWidth<768?9:12;try{return(await u.get("/filters",{params:{filter:o,page:t,limit:r}})).data}catch(e){console.error("Error fetching categories:",e)}},m=()=>{document.getElementById("subscription-form").addEventListener("submit",async t=>{var e,s,i;t.preventDefault();const c=t.target.elements.email,r=c.value;try{const n=await p(r);if(n){const a=((e=n.data)==null?void 0:e.message)||n.message||"Subscription successful!";l({text:a,duration:3e3,style:{background:"#4CAF50"},close:!0}).showToast(),c.value=""}}catch(n){const a=((i=(s=n.response)==null?void 0:s.data)==null?void 0:i.message)||n.message||"An error occurred. Please try again later.";l({text:a,duration:3e3,style:{background:"#FF5F6D"},close:!0}).showToast()}})};document.querySelector(".exercises-filter-input");const g=document.querySelector('button[data-name="Muscles"]'),y=document.querySelector(".excercises-categories-list");async function b(){if(g.classList.contains("active"))try{const o=await f("Muscles",1);console.log(o);const t=h(o.results);y.insertAdjacentHTML("beforeend",t)}catch(o){console.error("Error fetching categories:",o)}else{musclesExcercisesMarkup.innerHTML="";return}}b();function h(o){return o.map(t=>{const{filter:c,name:r,imgURL:e}=t;return` <li class="excercises-categories-item" data-body-part='${r}'>
			<button type="button" class="excercises-categories-btn"  alt="${r}" style='background: linear-gradient(0deg, rgba(17, 17, 17, 0.50) 0%, rgba(17, 17, 17, 0.50) 100%), url(${e}) no-repeat;
background-size: cover;
	background-position: center;'

				<div class="excercises-categories-info">
					<h3 class="excercises-category-title">${r}</h3>
					<p class="excercises-category-descr">${c}</p>
				</div>
			</button>
		</li> `}).join("")}document.addEventListener("DOMContentLoaded",()=>{m()});
//# sourceMappingURL=index.js.map
